events {}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 9003;
    client_header_buffer_size 16k;
    large_client_header_buffers 8 32k;

    location = /protocol/openid-connect/auth {
      proxy_pass http://host.docker.internal:9001/application/o/authorize/?client_id=$arg_client_id&redirect_to=$arg_redirect_to&redirect_uri=$arg_redirect_uri&response_type=$arg_response_type&scope=openid%20profile%20email&state=$arg_state;
      proxy_redirect ~^(/if/.*)$ http://192.168.1.6:9003$1;
      proxy_set_header Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /protocol/openid-connect/token {
      proxy_pass http://host.docker.internal:9001/application/o/token/;
      proxy_set_header Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /protocol/openid-connect/userinfo {
      proxy_pass http://host.docker.internal:9001/application/o/userinfo/;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass http://host.docker.internal:9001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Host 192.168.1.6:9003;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
