export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { href: "/requests", label: "Requests", icon: "Inbox" },
  { href: "/complaints", label: "Complaints", icon: "MessageSquareWarning" },
  { href: "/my-tasks", label: "My Tasks", icon: "ClipboardCheck" },
  { href: "/equipment", label: "Equipment", icon: "Wrench" },
  { href: "/scan", label: "Scan", icon: "ScanLine" },
  { href: "/work-orders", label: "Work Orders", icon: "ClipboardList" },
  { href: "/pm-schedules", label: "PM Schedule", icon: "CalendarCheck" },
  { href: "/parts", label: "Parts", icon: "Package" },
  { href: "/purchasing", label: "Purchasing", icon: "ShoppingCart" },
  { href: "/reference-standards", label: "Standards", icon: "Gauge" },
  { href: "/reports", label: "Reports", icon: "BarChart3" },
  { href: "/audit-log", label: "Audit Log", icon: "FileSearch" },
  { href: "/settings", label: "Settings", icon: "Settings" },
] as const
